### ISSUE TITLE
"Installation"

### ISSUE THREAD

**Issue by tcarlyle** [pablorusso/Spotify2.bundle#21]
Hei,
sorry if this is a silly question, but are there any additional steps in order to install/use the plugin?
I've copied the Spotify2.bundle to my plugin folders and made the plex user the owner of the folder.

Then, I've tried going to my plex channels and searching for spotify into the installed plug-ins, but I could not find it. Is there some other step needed? That is the first time I install a plug-in, so I may be missing something =S

**Comment by tcarlyle** [comment]
oops, it was jut a matter of restart of the server =D

**Comment by pablorusso** [comment]
Glad to see it worked.
Let me know anyway if you hit any other issue!

On Tue, Jul 7, 2015 at 5:32 PM, Thomas Vilarinho <notifications@github.com>
wrote:

> oops, it was jut a matter of restart of the server =D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pablorusso/Spotify2.bundle/issues/21#issuecomment-119327877>
> .
>



-- 
Pablo.-
http://about.me/russopablo
